version: '3.9'
services:
  my-api:
    image: otus.teaching.promocodefactory
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.2.3
    ports:
      - "27017:27017"