version: '3.9'
services:
  my-api:
    image: Otus.Teaching.PromoCodeFactory
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.2.3
    ports:
      - "27017:27017"